name: Self Test

permissions:
  contents: write
  pull-requests: write

on:
  push:
    # This turns off running for tags
    branches:
      - "**"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  self-test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Generate date
        id: generate-id
        run: |
          echo "id=$(uuidgen -t)" >> "${GITHUB_OUTPUT}"
      - name: Make fake ass branch
        run: |
          git checkout -b self-test/${{ steps.generate-id.outputs.id }}
          git push origin self-test/${{ steps.generate-id.outputs.id }}
      - uses: ./
        id: self-test
        with:
          head: self-test/${{ steps.generate-id.outputs.id }}
          base: master
          title: |
            Just a test ass branch
          body: |
            Just testinz
      - run: |
          echo "Created pull request ${{ fromJson(steps.self-test.outputs.pull-request).number }}"
      - name: Close pull request
        run: |
          echo "implement me"
